name: Main Pipeline

on:
  schedule:
    - cron: "30 20 * * *" # Agendado para 21:00 UTC

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Verificar variáveis de ambiente
        run: |
          if [ -z "${{ secrets.SUPABASE_MAIN_URL }}" ] || [ -z "${{ secrets.SUPABASE_PASSWORD_MAIN }}" ] || [ -z "${{ secrets.SUPABASE_USERNAME_MAIN }}" ]; then
            echo "Erro: Variáveis de ambiente ausentes."
            echo "Certifique-se de configurar SUPABASE_MAIN_URL, SUPABASE_PASSWORD_MAIN e SUPABASE_USERNAME_MAIN nos Secrets do GitHub."
            exit 1
          fi

      - name: Instalar PostgreSQL CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Aplicar migrações no Supabase (Main)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_MAIN_URL }}
          SUPABASE_USERNAME: ${{ secrets.SUPABASE_USERNAME_MAIN }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD_MAIN }}
        run: |
          echo "Aplicando migrações no banco de dados Supabase (Main)..."
          for file in $(ls migrations/*.sql); do
            echo "Executando $file..."
            PGPASSWORD=${SUPABASE_PASSWORD} psql -h ${SUPABASE_URL} -p 6543 -U postgres.mencmqtmgbknekwavnld -d postgres -f $file
          done

      - name: Deploy para GitHub Pages (Main)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Diretório onde o `index.html` está localizado
